# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_mess', models.FileField(upload_to='')),
                ('file_keyword', models.FileField(upload_to='')),
            ],
        ),
    ]
